language: php
    
php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=4.0.1 WP_MULTISITE=0
    - WP_VERSION=4.0 WP_MULTISITE=0
    - WP_VERSION=3.9 WP_MULTISITE=0
      
install:
    - composer install --dev
      
script: 
    - vendor/bin/wp-qa-syntax
    - vendor/bin/wp-qa-phpunit $WP_VERSION
